name: build
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Build Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: davidsiaw/picoci:latest
    - name: Build example
      run: |
        cd example
        make
    - name: Test example
      run: |
        cd example
        make test
